version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: poc
      RABBITMQ_DEFAULT_PASS: poc_password
    ports:
      - "15672:15672"
      - "5672:5672"